/*
 Navicat Premium Data Transfer

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 140013 (140013)
 Source Host           : localhost:5432
 Source Catalog        : weather
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140013 (140013)
 File Encoding         : 65001

 Date: 01/09/2024 13:29:49
*/


-- ----------------------------
-- Sequence structure for Locations_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Locations_Id_seq";
CREATE SEQUENCE "public"."Locations_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for WeatherData_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."WeatherData_Id_seq";
CREATE SEQUENCE "public"."WeatherData_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for Locations
-- ----------------------------
DROP TABLE IF EXISTS "public"."Locations";
CREATE TABLE "public"."Locations" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "CityName" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "CountryCode" varchar(2) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of Locations
-- ----------------------------
INSERT INTO "public"."Locations" VALUES (1, 'Anadyr', 'ru');
INSERT INTO "public"."Locations" VALUES (2, 'Sochi', 'ru');
INSERT INTO "public"."Locations" VALUES (3, 'Oslo', 'no');
INSERT INTO "public"."Locations" VALUES (4, 'Tromso', 'no');

-- ----------------------------
-- Table structure for WeatherData
-- ----------------------------
DROP TABLE IF EXISTS "public"."WeatherData";
CREATE TABLE "public"."WeatherData" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "TemperatureInCelsius" numeric NOT NULL,
  "LocationId" int4 NOT NULL,
  "Timestamp" timestamptz(6) NOT NULL
)
;

-- ----------------------------
-- Records of WeatherData
-- ----------------------------
INSERT INTO "public"."WeatherData" VALUES (5, 6.67, 1, '2024-09-01 09:50:10.927169+00');
INSERT INTO "public"."WeatherData" VALUES (6, 29.05, 2, '2024-09-01 09:50:10.927169+00');
INSERT INTO "public"."WeatherData" VALUES (7, 17.17, 3, '2024-09-01 09:50:10.927169+00');
INSERT INTO "public"."WeatherData" VALUES (8, 14.01, 4, '2024-09-01 09:50:10.927169+00');
INSERT INTO "public"."WeatherData" VALUES (9, 6.67, 1, '2024-09-01 09:51:10.808481+00');
INSERT INTO "public"."WeatherData" VALUES (10, 29.05, 2, '2024-09-01 09:51:10.808481+00');
INSERT INTO "public"."WeatherData" VALUES (11, 17.17, 3, '2024-09-01 09:51:10.808481+00');
INSERT INTO "public"."WeatherData" VALUES (12, 14.01, 4, '2024-09-01 09:51:10.808481+00');
INSERT INTO "public"."WeatherData" VALUES (13, 6.67, 1, '2024-09-01 09:52:10.821267+00');
INSERT INTO "public"."WeatherData" VALUES (14, 29.05, 2, '2024-09-01 09:52:10.821267+00');
INSERT INTO "public"."WeatherData" VALUES (15, 17.17, 3, '2024-09-01 09:52:10.821267+00');
INSERT INTO "public"."WeatherData" VALUES (16, 14.01, 4, '2024-09-01 09:52:10.821267+00');
INSERT INTO "public"."WeatherData" VALUES (17, 6.67, 1, '2024-09-01 09:53:10.868472+00');
INSERT INTO "public"."WeatherData" VALUES (18, 29.05, 2, '2024-09-01 09:53:10.868472+00');
INSERT INTO "public"."WeatherData" VALUES (19, 17.61, 3, '2024-09-01 09:53:10.868472+00');
INSERT INTO "public"."WeatherData" VALUES (20, 14.01, 4, '2024-09-01 09:53:10.868472+00');
INSERT INTO "public"."WeatherData" VALUES (21, 6.67, 1, '2024-09-01 09:54:10.905668+00');
INSERT INTO "public"."WeatherData" VALUES (22, 29.05, 2, '2024-09-01 09:54:10.905668+00');
INSERT INTO "public"."WeatherData" VALUES (23, 17.82, 3, '2024-09-01 09:54:10.905668+00');
INSERT INTO "public"."WeatherData" VALUES (24, 14.01, 4, '2024-09-01 09:54:10.905668+00');
INSERT INTO "public"."WeatherData" VALUES (25, 6.67, 1, '2024-09-01 09:55:10.932193+00');
INSERT INTO "public"."WeatherData" VALUES (26, 29.05, 2, '2024-09-01 09:55:10.932193+00');
INSERT INTO "public"."WeatherData" VALUES (27, 17.82, 3, '2024-09-01 09:55:10.932193+00');
INSERT INTO "public"."WeatherData" VALUES (28, 14.01, 4, '2024-09-01 09:55:10.932193+00');
INSERT INTO "public"."WeatherData" VALUES (29, 6.67, 1, '2024-09-01 09:56:10.959271+00');
INSERT INTO "public"."WeatherData" VALUES (30, 29.05, 2, '2024-09-01 09:56:10.959271+00');
INSERT INTO "public"."WeatherData" VALUES (31, 17.82, 3, '2024-09-01 09:56:10.959271+00');
INSERT INTO "public"."WeatherData" VALUES (32, 14.01, 4, '2024-09-01 09:56:10.959271+00');
INSERT INTO "public"."WeatherData" VALUES (33, 6.67, 1, '2024-09-01 09:57:11.010744+00');
INSERT INTO "public"."WeatherData" VALUES (34, 29.05, 2, '2024-09-01 09:57:11.010744+00');
INSERT INTO "public"."WeatherData" VALUES (35, 17.82, 3, '2024-09-01 09:57:11.010744+00');
INSERT INTO "public"."WeatherData" VALUES (36, 14.01, 4, '2024-09-01 09:57:11.010744+00');
INSERT INTO "public"."WeatherData" VALUES (37, 6.67, 1, '2024-09-01 09:58:11.040585+00');
INSERT INTO "public"."WeatherData" VALUES (38, 29.05, 2, '2024-09-01 09:58:11.040585+00');
INSERT INTO "public"."WeatherData" VALUES (39, 17.82, 3, '2024-09-01 09:58:11.040585+00');
INSERT INTO "public"."WeatherData" VALUES (40, 14.01, 4, '2024-09-01 09:58:11.040585+00');
INSERT INTO "public"."WeatherData" VALUES (41, 6.67, 1, '2024-09-01 09:59:11.085786+00');
INSERT INTO "public"."WeatherData" VALUES (42, 29.05, 2, '2024-09-01 09:59:11.085786+00');
INSERT INTO "public"."WeatherData" VALUES (43, 17.82, 3, '2024-09-01 09:59:11.085786+00');
INSERT INTO "public"."WeatherData" VALUES (44, 14.01, 4, '2024-09-01 09:59:11.085786+00');
INSERT INTO "public"."WeatherData" VALUES (45, 6.67, 1, '2024-09-01 10:00:11.11468+00');
INSERT INTO "public"."WeatherData" VALUES (46, 29.05, 2, '2024-09-01 10:00:11.11468+00');
INSERT INTO "public"."WeatherData" VALUES (47, 17.82, 3, '2024-09-01 10:00:11.11468+00');
INSERT INTO "public"."WeatherData" VALUES (48, 14.01, 4, '2024-09-01 10:00:11.11468+00');
INSERT INTO "public"."WeatherData" VALUES (49, 6.67, 1, '2024-09-01 10:01:11.155151+00');
INSERT INTO "public"."WeatherData" VALUES (50, 29.05, 2, '2024-09-01 10:01:11.155151+00');
INSERT INTO "public"."WeatherData" VALUES (51, 17.82, 3, '2024-09-01 10:01:11.155151+00');
INSERT INTO "public"."WeatherData" VALUES (52, 14.01, 4, '2024-09-01 10:01:11.155151+00');
INSERT INTO "public"."WeatherData" VALUES (53, 6.67, 1, '2024-09-01 10:02:11.20597+00');
INSERT INTO "public"."WeatherData" VALUES (54, 29.05, 2, '2024-09-01 10:02:11.20597+00');
INSERT INTO "public"."WeatherData" VALUES (55, 17.82, 3, '2024-09-01 10:02:11.20597+00');
INSERT INTO "public"."WeatherData" VALUES (56, 14.01, 4, '2024-09-01 10:02:11.20597+00');
INSERT INTO "public"."WeatherData" VALUES (57, 6.67, 1, '2024-09-01 10:03:11.248087+00');
INSERT INTO "public"."WeatherData" VALUES (58, 29.05, 2, '2024-09-01 10:03:11.248087+00');
INSERT INTO "public"."WeatherData" VALUES (59, 17.82, 3, '2024-09-01 10:03:11.248087+00');
INSERT INTO "public"."WeatherData" VALUES (60, 14.01, 4, '2024-09-01 10:03:11.248087+00');
INSERT INTO "public"."WeatherData" VALUES (61, 6.67, 1, '2024-09-01 10:04:11.294338+00');
INSERT INTO "public"."WeatherData" VALUES (62, 29.05, 2, '2024-09-01 10:04:11.294338+00');
INSERT INTO "public"."WeatherData" VALUES (63, 18.77, 3, '2024-09-01 10:04:11.294338+00');
INSERT INTO "public"."WeatherData" VALUES (64, 14.01, 4, '2024-09-01 10:04:11.294338+00');
INSERT INTO "public"."WeatherData" VALUES (65, 6.67, 1, '2024-09-01 10:05:11.324316+00');
INSERT INTO "public"."WeatherData" VALUES (66, 29.05, 2, '2024-09-01 10:05:11.324316+00');
INSERT INTO "public"."WeatherData" VALUES (67, 18.77, 3, '2024-09-01 10:05:11.324316+00');
INSERT INTO "public"."WeatherData" VALUES (68, 14.01, 4, '2024-09-01 10:05:11.324316+00');
INSERT INTO "public"."WeatherData" VALUES (69, 6.67, 1, '2024-09-01 10:06:11.337056+00');
INSERT INTO "public"."WeatherData" VALUES (70, 29.05, 2, '2024-09-01 10:06:11.337056+00');
INSERT INTO "public"."WeatherData" VALUES (71, 18.77, 3, '2024-09-01 10:06:11.337056+00');
INSERT INTO "public"."WeatherData" VALUES (72, 14.01, 4, '2024-09-01 10:06:11.337056+00');
INSERT INTO "public"."WeatherData" VALUES (73, 6.67, 1, '2024-09-01 10:07:11.383666+00');
INSERT INTO "public"."WeatherData" VALUES (74, 29.05, 2, '2024-09-01 10:07:11.383666+00');
INSERT INTO "public"."WeatherData" VALUES (75, 18.77, 3, '2024-09-01 10:07:11.383666+00');
INSERT INTO "public"."WeatherData" VALUES (76, 14.01, 4, '2024-09-01 10:07:11.383666+00');
INSERT INTO "public"."WeatherData" VALUES (77, 6.67, 1, '2024-09-01 10:08:11.418065+00');
INSERT INTO "public"."WeatherData" VALUES (78, 29.05, 2, '2024-09-01 10:08:11.418065+00');
INSERT INTO "public"."WeatherData" VALUES (79, 18.77, 3, '2024-09-01 10:08:11.418065+00');
INSERT INTO "public"."WeatherData" VALUES (80, 14.01, 4, '2024-09-01 10:08:11.418065+00');
INSERT INTO "public"."WeatherData" VALUES (81, 6.67, 1, '2024-09-01 10:09:11.460939+00');
INSERT INTO "public"."WeatherData" VALUES (82, 29.05, 2, '2024-09-01 10:09:11.460939+00');
INSERT INTO "public"."WeatherData" VALUES (83, 18.81, 3, '2024-09-01 10:09:11.460939+00');
INSERT INTO "public"."WeatherData" VALUES (84, 14.01, 4, '2024-09-01 10:09:11.460939+00');
INSERT INTO "public"."WeatherData" VALUES (85, 6.67, 1, '2024-09-01 10:10:11.511979+00');
INSERT INTO "public"."WeatherData" VALUES (86, 29.05, 2, '2024-09-01 10:10:11.511979+00');
INSERT INTO "public"."WeatherData" VALUES (87, 18.81, 3, '2024-09-01 10:10:11.511979+00');
INSERT INTO "public"."WeatherData" VALUES (88, 14.01, 4, '2024-09-01 10:10:11.511979+00');
INSERT INTO "public"."WeatherData" VALUES (89, 6.67, 1, '2024-09-01 10:11:11.545573+00');
INSERT INTO "public"."WeatherData" VALUES (90, 29.05, 2, '2024-09-01 10:11:11.545573+00');
INSERT INTO "public"."WeatherData" VALUES (91, 18.81, 3, '2024-09-01 10:11:11.545573+00');
INSERT INTO "public"."WeatherData" VALUES (92, 14.01, 4, '2024-09-01 10:11:11.545573+00');
INSERT INTO "public"."WeatherData" VALUES (93, 6.67, 1, '2024-09-01 10:12:11.577768+00');
INSERT INTO "public"."WeatherData" VALUES (94, 29.05, 2, '2024-09-01 10:12:11.577768+00');
INSERT INTO "public"."WeatherData" VALUES (95, 18.81, 3, '2024-09-01 10:12:11.577768+00');
INSERT INTO "public"."WeatherData" VALUES (96, 14.01, 4, '2024-09-01 10:12:11.577768+00');

-- ----------------------------
-- Table structure for __EFMigrationsHistory
-- ----------------------------
DROP TABLE IF EXISTS "public"."__EFMigrationsHistory";
CREATE TABLE "public"."__EFMigrationsHistory" (
  "MigrationId" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "ProductVersion" varchar(32) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of __EFMigrationsHistory
-- ----------------------------
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20240901094121_Initial', '6.0.0');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Locations_Id_seq"
OWNED BY "public"."Locations"."Id";
SELECT setval('"public"."Locations_Id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."WeatherData_Id_seq"
OWNED BY "public"."WeatherData"."Id";
SELECT setval('"public"."WeatherData_Id_seq"', 96, true);

-- ----------------------------
-- Auto increment value for Locations
-- ----------------------------
SELECT setval('"public"."Locations_Id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table Locations
-- ----------------------------
ALTER TABLE "public"."Locations" ADD CONSTRAINT "PK_Locations" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for WeatherData
-- ----------------------------
SELECT setval('"public"."WeatherData_Id_seq"', 96, true);

-- ----------------------------
-- Indexes structure for table WeatherData
-- ----------------------------
CREATE INDEX "IX_WeatherData_LocationId" ON "public"."WeatherData" USING btree (
  "LocationId" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table WeatherData
-- ----------------------------
ALTER TABLE "public"."WeatherData" ADD CONSTRAINT "PK_WeatherData" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table __EFMigrationsHistory
-- ----------------------------
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");

-- ----------------------------
-- Foreign Keys structure for table WeatherData
-- ----------------------------
ALTER TABLE "public"."WeatherData" ADD CONSTRAINT "FK_WeatherData_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "public"."Locations" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
